### ISSUE TITLE
CSS v2.0

### ISSUE THREAD

**Issue by harzavad** [harzavad/the-merchant#10]
@Shan-Mei  problemo

My hyperlinks do not work properly, the longer ones especially. Can you check it out?

**Comment by Shan-Mei** [comment]
I will look tmr.

**Comment by spicata** [comment]
Unless your really want that sliding animations, you could default just to:

```css
a:hover {
    background-color: #993C19;
    color: #FADE8F;
}

a {
    /* the rest of the css */
    transition: color .3s ease-in-out, background-color .3s ease-in-out;
}
```
